### ISSUE TITLE
여행지 추천 관련 문제

### ISSUE THREAD

**Issue by wl2258** [5iyo/diary#11]
1. 오픈 api (날씨, 관광지)를 사용하면 데이터 양이 많아서 그런지 굉장히 오래 걸린다. (거의 2분 소요)
2. 관광지 추천 api 가 올해 기준이 아니라서 2020년, 2019년 축제 정보가 존재한다.

일단 날씨가 맑은 지역을 먼저 보여주고 사용자가 해당 지역을 선택하면 그 지역의 추천 관광지 정보를 보내주는 방법으로 해결하면 어떨지... 2번 문제가 남아있긴 하지만...
어떻게 해결하면 좋을지 다들 의견 부탁드려요!

**Comment by yunzung** [comment]
관광지추천 api에 지역마다 특정 장소(경주면 동궁과월지)도 포함돼있으면 축제 정보를 거르고 그런 장소만 정보로 내보낼 수 있나요...?

**Comment by JYeonJun** [comment]
아니면 1번 문제를 페이지 형식으로
예를 들어 1페이지면 5개만 우선 보여주고
2페이지면 다음 5개씩 보여주는 형식으로 해도 될 것 같아요.

만약에 추천 여행지를 페이지 형식이 아닌 위 아래 스크롤로 연속해서 보여주는 거면 하나씩 선택해서 보여주는 형식으로 해야하지 않을까 생각합니다.
