### ISSUE TITLE
읽어보시고 의견 부탁드립니다

### ISSUE THREAD

**Issue by JYeonJun** [5iyo/diary#5]
현재 Trip (여행) 테이블의 필드 목록은 다음과 같습니다.
![image](https://user-images.githubusercontent.com/97449471/200117211-50a1d8cc-e7ec-427a-9ac3-3061bdb929cf.png)

사용자가 여행 후 일기를 작성하면 지도 위에 좌표가 필요한데 Trip 테이블의 위도, 경도 필드가 이 역할을 수행합니다.
그리고 해당 좌표에 위치하는 마커를 클릭하면 해당 여행의 일기들을 조회할 수 있습니다.

여기서 제가 구하고 싶은 의견은 Trip 테이블에 title 필드를 추가해 해당 여행의 title을 추가하는 건 어떨까?? 입니다.
title은 해당 여행의 키워드?? 키포인트?? 를 나타낼 수 있을 것 같습니다.
마커를 클릭하면 이동하는 일기 리스트 조회 페이지 최상단에 쓰일 수도 있고 다른 곳에서도 쓰일 수 있지 않을까?? 하는 의견입니다.
![image](https://user-images.githubusercontent.com/97449471/200117414-82549937-decf-4e1b-bb42-69346a863072.png)

**Comment by Jeonwoojae** [comment]
여행에 대해 지역 이름 말고 추가로 tag를 추가하고 싶다는 말씀이신가요?? 예를 들면 (핑크뮬리 명소) 같이?

**Comment by JYeonJun** [comment]
네!! 맞아요

**Comment by JYeonJun** [comment]
아 혹시 tag가 해시태그 말하는 걸까요??
음.. 여기서 제가 말하는 title은 일기에서 제목 쓰듯이 여행에도 제목?? 같은 역할로 말한 거예요.

**Comment by yunzung** [comment]
title 필드가 없으면 만약 부산 여행을 두 번 갔을 때 부산에 대한 두 개의 일기를 구분하는 것은 위도, 경도가 되는 건가요???

**Comment by JYeonJun** [comment]
그건 목요일에 
"만약에 일정한 텀을 두고 여행지가 겹치면 지도에 어떻게 표시할 것인가"
준식이랑 대화해 봤는데 그때 결론이 나지 않았어요.
어떻게 할지 정해야 할 것 같아요.

**Comment by qkrwnstlr** [comment]
Trip에 title이 들어가는 거는 필요할꺼 같네요

**Comment by yunzung** [comment]
그러면 title로 일기를 구분하면 될 거 같은데 지도에 마커는 어떻게 표시해야할 지 모르겠네요

**Comment by yunzung** [comment]
저도 title은 필요한 것 같습니다!!
