### ISSUE TITLE
의견 있습니다.

### ISSUE THREAD

**Issue by JYeonJun** [5iyo/diary#6]
여행 테이블 필드로

**- 여행 기간**
ex) 2022.11.05 ~ 2022.11.07

필드가 있으면 어떨까 하는 저의 소소한 의견입니다.

**Comment by Jeonwoojae** [comment]
![image](https://user-images.githubusercontent.com/78198709/200118260-df3ac3bf-c518-4d1c-9a21-7e28f687a459.png)
현재 (여행)1:N(다이어리)관계라서 여행 기간을 여행 테이블에 못 두지 않을까요??

**Comment by JYeonJun** [comment]
diaries 필드는 Trip 테이블에 들어가지 않아서 상관없을 것 같아요
그냥 Trip에서 Diary 참조하려고 만든 필드라서 Diary랑은 상관없이 
![image](https://user-images.githubusercontent.com/97449471/200118426-626ede8d-cfc5-4cf3-a694-9dbf655d8208.png)
이렇게 추가적인 필드로 저장하면 돼서 문제 없지 않을까요?

**Comment by Jeonwoojae** [comment]
아 제가 전체 구조를 잘못 봤었네요ㅎ 죄송합니다.
여행 기간 저장하는건 뒤에 여러 다이어리들 마다 다른 날짜로 기록하기에 좋을 것 같아요!
