### ISSUE TITLE
마커 문제!!

### ISSUE THREAD

**Issue by JYeonJun** [5iyo/diary#7]
텀을 두고 동일한 여행지로 여행을 갔다면 지도 위에 마커를 어떻게 표현할 것인가

**Comment by yunzung** [comment]
마커는 하나만 찍고 마커 클릭하면 그냥 그 지역에 대한 여행일기를 모두 보여주는 건 어떨까요? 일기 title이랑 기간이 있으니까 다른 날에 여행했다는 걸 사용자도 알 수 있으니까용

**Comment by JYeonJun** [comment]
좋은 것 같아요.

그런데 또 생각해봐야 하는 부분이
만약에 사용자가 구미를 두 번 여행 했을 때 지도에서 구미를 찾아 두 번 마커를 찍을텐데
사용자가 직접 손가락으로 클릭하면 이전 마커랑 동일한 좌표를 정확히 클릭하지 않는 이상 같은 구미여도 마커가 2개 생기는 거라

마커를 어떻게 찍을지도 한 번 고민해봐야 할 것 같아요.
1. 검색창에 지역을 검색해서 해당 좌표에 마커가 생기도록 한다.
-> 그러면 동일한 여행지여도 위 의견처럼 해당 지역에 대한 여행일기를 모두 보여주던지 할 수 있을 것 같아요.

2. 사용자가 직접 클릭해 마커가 생기도록 한다.
-> 음..

**Comment by Jeonwoojae** [comment]
직접 클릭은 어려울 것 같고 일정 거리 안이라면 마커 하나로 두고 누를 경우 새로운 리스트로 여행 일기들을 나열해주는 건 어떨까요?

**Comment by Jeonwoojae** [comment]
이건 마커가 여러 개로 늘어났을 때 사용자가 지도를 축소했을 경우에도 비슷한 문제가 생길 것 같아요

**Comment by yunzung** [comment]
저는 장소 검색해서 일기 쓰는 것으로 알고 있고 그렇게 구현 중이었습니다 ...!
그래서 사용자가 구미 여행을 두 번 했을 때 구미시로만 검색해서 작성하면 해당 지역에 대한 여행 일기를 모두 보여주고,
구미시 옥계, 구미시 산동 이렇게 여행했으면 좀 더 자세히 검색해서 옥계와 산동에 마커를 생성하는 걸로 해서 그냥 사용자 편한대로 하는 것으로 생각했어요.

**Comment by JYeonJun** [comment]
제가 잘 몰라서 그런데 지금 말하는 게
다음 두 가지 중 어느 것이 맞을까요?
1번
![image](https://user-images.githubusercontent.com/97449471/200121093-1c6c3a1d-8031-442a-87eb-96767addad83.png)

2번
![image](https://user-images.githubusercontent.com/97449471/200121098-a7c40fca-df9a-4498-a815-048e8e96487f.png)

**Comment by yunzung** [comment]
음.. 1번이 보기 좋을 것 같아요 여행 리스트에 기간도 같이 표시되면 어떨까요?

**Comment by JYeonJun** [comment]
네 1번 방식처럼 하면 Travel의 title 필드로 여행  제목이랑 startDate, endDate 필드로 여행 기간도 표시할 수 있을 것 같아요.
