### ISSUE TITLE
일기 리스트 조회 페이지

### ISSUE THREAD

**Issue by JYeonJun** [5iyo/diary#9]
지도에서 마커를 클릭하고
특정 여행에 대한 일기 리스트 조회 페이지가 다음과 같이 존재할 때
![image](https://user-images.githubusercontent.com/97449471/200127988-0457912e-f691-4e1f-8ad4-94fcdc29c481.png)
Diary1, 2, 3, 4, 5 대신
해당 일기에 대한 간단한 정보를 보여주는 게 좋을 것 같은데 프론트에서 어떤 정보가 필요한지 의견이 궁금합니다.

일단 제가 생각하는 내용은 다음과 같습니다.
1. 일기 제목
2. 여행 날짜
3. 날씨
4. 일기 생성 날짜
5. 일기 최종 수정 날짜

![image](https://user-images.githubusercontent.com/97449471/200128148-183d3a96-fa0c-497e-a45c-522cb13f885b.png)

의견 부탁드립니다.

**Comment by yunzung** [comment]
음 좋은데 생성 시간과 수정 시간까지 다 띄우면 리스트 하나가 좀 복잡해 보일 것 같아서 저는 일기 제목과 여행 날짜, 날씨만 해도 저는 괜찮을 것 같습니다

**Comment by JYeonJun** [comment]
네!! 수정할게요

**Comment by JYeonJun** [comment]
나중에 일기 조회할 때 필요해서 일기id도 같이 보낼게요.
